version: 0.2

cache:
  paths:
    - '/root/.aws/*'

phases:
  install:
    commands:
      - |
        if [ ! -f "/root/.aws/cli/cache" ]; then
          apk --no-cache add aws-cli
        fi
  pre_build:
    commands:
      - echo $(aws ecr get-login-password --region us-east-1) | docker login --username AWS --password-stdin 424132437436.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t tp-api .
      - docker tag tp-api:latest 424132437436.dkr.ecr.us-east-1.amazonaws.com/tp-api:latest
  post_build:
    commands:
      - docker push 424132437436.dkr.ecr.us-east-1.amazonaws.com/tp-api:latest
artifacts:
  type: CODEPIPELINE
