version: 0.2

phases:
  install:
    commands:
      - yum install -y aws-cli
      - yum install -y docker
      - service docker start
  pre_build:
    commands:
      - echo $(aws ecr get-login-password --region us-east-1) | docker login --username AWS --password-stdin 424132437436.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t tp-api .
      - docker tag tp-api:latest 424132437436.dkr.ecr.us-east-1.amazonaws.com/tp-api:latest
  post_build:
    commands:
      - docker push 424132437436.dkr.ecr.us-east-1.amazonaws.com/tp-api:latest
artifacts:
  type: CODEPIPELINE
